[project]
name = "rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium[box2d]>=1.2.3",
    "pygame>=2.6.1",
    "stable-baselines3>=2.7.1",
    "swig>=4.4.1",
]
